### ISSUE TITLE
Drag button in tasks

### ISSUE THREAD

**Issue by safin-sys** [drkPrince/agilix#1]
Hi, it will be really nice if you added a drag button/section in the tasks component. Trying to drag the tasks from one list to another results in a lot of misclicks to the task itself, so a drag button/section will be awesome.

**Comment by drkPrince** [comment]
Hey, Sorry for the late response. 
Regarding misclicks, where are they happening, mobile or the desktop?

A dragger could be added to the Task, but it would make it less minimal and overall kinda filled.

**Comment by safin-sys** [comment]
Misclicks are mostly a desktop problem (for me).

I agree that a dragger would make the UI more cluttered but a dragger which is only visible in hover will get rid of that problem.

**Comment by drkPrince** [comment]
How do you address the fact that the hover states on mobile are useless?
